---
- name: Preflight checks
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Get ostree fact
      ansible.builtin.import_role:
        name: common
        tasks_from: ostree.yml

    - name: Run variable preflight checks
      ansible.builtin.import_role:
        name: preflight
        tasks_from: core.yml

- name: Preflight node checks
  hosts: ansiblemcp
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      become: true

    - name: Gather regular user id, uid and home dir
      ansible.builtin.setup:
        filter:
          - 'ansible_user_id'
          - 'ansible_user_uid'
          - 'ansible_user_dir'

    - name: Run node preflight checks
      ansible.builtin.import_role:
        name: preflight
        tasks_from: ansiblemcp.yml

    - name: Run node preflight checks
      ansible.builtin.import_role:
        name: preflight
        tasks_from: nodes.yml

- name: Install common container components
  hosts: ansiblemcp
  any_errors_fatal: true
  gather_facts: false
  become: false
  tasks:
    - name: Install and configure podman
      ansible.builtin.import_role:
        name: common

- name: Install the Ansible MCP Server
  any_errors_fatal: true
  hosts: ansiblemcp
  gather_facts: false
  become: false
  tasks:
    - name: Install and configuration Ansible MCP Server
      ansible.builtin.import_role:
        name: ansiblemcp

...
