---
- name: Create systemd user directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Create metrics-utility-gather timer
  ansible.builtin.template:
    src: metrics-utility-gather.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/metrics-utility-gather.timer"
    mode: '0644'

- name: Create metrics-utility-build-report timer
  ansible.builtin.template:
    src: metrics-utility-build-report.timer.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/metrics-utility-build-report.timer"
    mode: '0644'

- name: Enable and start timers
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - metrics-utility-gather.timer
    - metrics-utility-build-report.timer
...
