---
- name: Pull the container image
  containers.podman.podman_image:
    name: '{{ item }}'
    pull: true
    force: '{{ container_pull_images | bool }}'
    validate_certs: '{{ registry_tls_verify }}'
    arch: '{{ container_image_arch | default(omit) }}'
  environment:
    HTTP_PROXY: "{{ http_proxy | default('') }}"
    HTTPS_PROXY: "{{ https_proxy | default('') }}"
    NO_PROXY: "{{ no_proxy | default('') }}"

- name: Save the container image
  containers.podman.podman_save:
    dest: '{{ _bundle_images }}/{{ image }}.tar'
    image: '{{ item }}'
  vars:
    image: '{{ (item | basename).split(":")[0] }}'

- name: Compress the container image
  ansible.builtin.command: '{{ container_compress }} {{ _bundle_images }}/{{ image }}.tar'
  args:
    creates: '{{ _bundle_images }}/{{ image }}.tar.gz'
  vars:
    image: '{{ (item | basename).split(":")[0] }}'

- name: Delete the container image
  containers.podman.podman_image:
    name: '{{ item }}'
    state: absent
...
