---
- name: Ensure lightspeed admin password is provided
  ansible.builtin.assert:
    that:
      - lightspeed_admin_password is defined
      - lightspeed_admin_password | length
    fail_msg: 'lightspeed_admin_password must be set and not empty'

- name: Ensure lightspeed postgresql sslmode is a valid choice
  ansible.builtin.assert:
    that:
      - lightspeed_pg_sslmode in ['disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full']
    fail_msg: 'Invalid lightspeed postgresql sslmode value. Only disable, allow, prefer, require, verify-ca and verify-full values are allowed'
  when: lightspeed_pg_sslmode is defined

- name: Ensure lightspeed postgresql host is provided
  ansible.builtin.assert:
    that:
      - lightspeed_pg_host is defined
      - lightspeed_pg_host | length
    fail_msg: 'lightspeed_pg_host must be set and not empty'

- name: Ensure lightspeed postgresql password is provided
  ansible.builtin.assert:
    that:
      - lightspeed_pg_password is defined
      - lightspeed_pg_password | length
    fail_msg: 'lightspeed_pg_password must be set and not empty'
  when: not lightspeed_pg_cert_auth | default(false) | bool

- name: When using lightspeed TLS authentication
  when:
    - lightspeed_pg_cert_auth is defined
    - lightspeed_pg_cert_auth | bool
  block:
    - name: Ensure using an external database
      ansible.builtin.assert:
        that:
          - groups.get('database', []) | length == 0
        fail_msg: 'Only external database topology supports postgresql TLS authentication'

    - name: Ensure lightspeed TLS certificate/key are provided
      ansible.builtin.assert:
        that:
          - lightspeed_pg_tls_cert is defined
          - lightspeed_pg_tls_cert | length
          - lightspeed_pg_tls_key is defined
          - lightspeed_pg_tls_key | length
          - custom_ca_cert is defined
          - custom_ca_cert | length
        fail_msg: 'lightspeed_pg_tls_cert, lightspeed_pg_tls_key and custom_ca_cert must be set and not empty'

    - name: Ensure lightspeed TLS certificate/key are provided with postgresql authentication enabled
      ansible.builtin.assert:
        that:
          - lightspeed_pg_sslmode is defined
          - lightspeed_pg_sslmode in ['verify-ca', 'verify-full']
        fail_msg: 'lightspeed_pg_sslmode must be set and using either verify-ca or verify-full value'

- name: Ensure lightspeed chatbot default provider is a valid choice
  ansible.builtin.assert:
    that:
      - lightspeed_chatbot_default_provider in ['rhoai', 'openai', 'azure']
    fail_msg: 'lightspeed_chatbot_default_provider must be set to any of the supported providers'
  when:
    - lightspeed_chatbot_model_url is defined
    - lightspeed_chatbot_default_provider is defined

- name: When using lightspeed chatbot, assert model configuration.
  ansible.builtin.assert:
    that:
      - lightspeed_chatbot_model_api_key is defined
      - lightspeed_chatbot_model_id is defined
    fail_msg: 'lightspeed_chatbot_model_api_key and lightspeed_chatbot_model_id must be set and not empty'
  when: lightspeed_chatbot_model_url is defined

- name: When using lightspeed mcp-lightspeed
  ansible.builtin.assert:
    that:
      - lightspeed_chatbot_model_url is defined
    fail_msg: 'lightspeed_chatbot_model_url must be set when using mcp-lightspeed'
  when:
    - lightspeed_mcp_lightspeed_enabled is defined
    - lightspeed_mcp_lightspeed_enabled | bool

- name: When using lightspeed mcp-controller
  when:
    - lightspeed_mcp_controller_enabled is defined
    - lightspeed_mcp_controller_enabled | bool
  block:
    - name: Ensure Lightspeed Chatbot is defined
      ansible.builtin.assert:
        that:
          - lightspeed_chatbot_model_url is defined
        fail_msg: 'lightspeed_chatbot_model_url must be set when using mcp-controller'
    - name: Ensure automation controller is enabled
      ansible.builtin.assert:
        that:
          - groups.get('automationcontroller', []) | length > 0
        fail_msg: 'automationcontroller must be enabled when using lightspeed-mcp-controller'

- name: When using lightspeed WCA on-prem, assert WCA username is defined
  ansible.builtin.assert:
    that:
      - lightspeed_wca_model_username is defined
    fail_msg: 'lightspeed_wca_model_username must be set when using an WCA on-prem deployment'
  when: lightspeed_wca_model_api_key is defined and lightspeed_wca_model_type == "wca-onprem"

- name: Only WCA cloud supports using an external IDP
  ansible.builtin.assert:
    that:
      - lightspeed_wca_model_type == "wca"
    fail_msg: 'lightspeed_wca_model_type must be "wca" (cloud) when using an IDP'
  when: lightspeed_wca_idp_url is defined

- name: WCA IDP authentication information checks.
  ansible.builtin.assert:
    that:
      - lightspeed_wca_idp_login is defined
      - lightspeed_wca_idp_password is defined
    fail_msg: 'WCA IDP missing login/password'
  when: lightspeed_wca_idp_url is defined
...
