---
- name: Include core checks
  ansible.builtin.include_tasks: core.yml

- name: Include database checks
  ansible.builtin.include_tasks: database.yml

- name: Include redis checks
  ansible.builtin.include_tasks: redis.yml

- name: Include controller checks
  ansible.builtin.include_tasks: automationcontroller.yml
  when: groups.get('automationcontroller', []) | length > 0

- name: Include hub checks
  ansible.builtin.include_tasks: automationhub.yml
  when: groups.get('automationhub', []) | length > 0

- name: Include eda checks
  ansible.builtin.include_tasks: automationeda.yml
  when: groups.get('automationeda', []) | length > 0

- name: Include lightspeed checks
  ansible.builtin.include_tasks: ansiblelightspeed.yml
  when: groups.get('ansiblelightspeed', []) | length > 0

- name: Include automation metrics checks
  ansible.builtin.include_tasks: automationmetrics.yml
  when: groups.get('automationmetrics', []) | length > 0

- name: Include receptor checks
  ansible.builtin.include_tasks: receptor.yml
  when: groups.get('execution_nodes', []) | length > 0

- name: Include gateway checks
  ansible.builtin.include_tasks: automationgateway.yml

- name: Validate feature flags
  when: feature_flags is defined
  block:
    - name: Ensure feature_flags is a dictonary
      ansible.builtin.assert:
        that:
          - feature_flags is not string
          - feature_flags is iterable
          - feature_flags is mapping
        fail_msg: 'feature_flags variable must be a dictionary'

    - name: Ensure feature_flags keys/values are valid
      ansible.builtin.assert:
        that:
          - item.key | upper is match('^FEATURE_')
          - item.value is boolean
        fail_msg: 'keys must be prefixed with feature_ and values must be boolean'
      loop: '{{ feature_flags | dict2items }}'
...
