---
- name: Run automation metrics database migrations
  containers.podman.podman_container:
    name: automation-metrics-init
    image: '{{ _automationmetrics_image }}'
    command: "/app/scripts/init.sh"
    entrypoint: ""
    detach: false
    rm: true
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    secrets: '{{ _common_secrets }}'
    volume: '{{ _common_volumes }}'
    env: '{{ _automationmetrics_env }}'
  register: _migrate
  changed_when: "'Initializing system tasks' in _migrate.stdout"
  retries: 5
  delay: 60
  until: _migrate is not failed
  run_once: true
...
