---
- name: Set automation metrics facts
  ansible.builtin.include_tasks: facts.yml

- name: Create the automation metrics directories
  ansible.builtin.file:
    path: '{{ automationmetrics_config_path }}'
    mode: '0770'
    state: directory

- name: Stop automation metrics systemd services
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: stopped

- name: Unarchive the automation metrics data
  ansible.builtin.unarchive:
    src: '{{ hostvars["localhost"]["_backup_dir"] }}/automationmetrics_{{ inventory_hostname }}.{{ automationmetrics_archive_extension }}'
    dest: '{{ ansible_user_dir }}'
    exclude:
      - 'aap/tls'
      - '.local/share/containers/storage/secrets/'

- name: Set automation metrics secret facts
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_secrets.yml
  vars:
    backup_file: '{{ hostvars["localhost"]["_backup_dir"] }}/automationmetrics_{{ inventory_hostname }}.{{ automationmetrics_archive_extension }}'

- name: Update the relevant automation metrics secrets
  containers.podman.podman_secret:
    name: "{{ item }}"
    data: "{{ lookup('ansible.builtin.vars', '__old_' + item) | b64decode }}"
  loop: '{{ _automationmetrics_restore_secrets }}'
  no_log: true
  vars:
    _automationmetrics_restore_secrets: >-
      {{
        ((not automationmetrics_pg_cert_auth | bool) |
        ternary(['automationmetrics_pg_password', 'automationmetrics_controller_read_pg_password'], []))
        + ['automationmetrics_secret_key']
      }}

- name: Import postgresql TLS certificate and key
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
    remote_src: true
  loop:
    - src: '{{ ansible_user_dir }}/aap/automationmetrics/config/postgresql.cert'
      dest: '{{ automationmetrics_config_path }}/postgresql.cert'
      mode: '0640'
    - src: '{{ ansible_user_dir }}/aap/automationmetrics/config/postgresql.key'
      dest: '{{ automationmetrics_config_path }}/postgresql.key'
      mode: '0400'
  when: automationmetrics_pg_cert_auth | bool
  failed_when: false

- name: Reconfigure containers
  ansible.builtin.include_tasks: containers.yml
  vars:
    __containers_recreate: true

- name: Find the automation metrics postgresql database
  ansible.builtin.find:
    path: '{{ ansible_user_dir }}/aap/backups'
    patterns:
      - '{{ automationmetrics_pg_database }}.{{ db_compressed_extension }}'
      - '{{ automationmetrics_pg_database }}.{{ db_decompressed_extension }}'
  register: _automationmetrics_db_file

- name: Create postgresql CLI aliases
  ansible.builtin.include_role:
    name: postgresql
    tasks_from: cli.yml
  vars:
    _postgresql_socket: '{{ automationmetrics_pg_socket | default("") }}'
    _postgresql_cert_auth: '{{ automationmetrics_pg_cert_auth }}'
    _postgresql_src_dir: '{{ automationmetrics_config_path }}'
    _postgresql_dest_dir: '{{ automationmetrics_config_path }}'
    _postgresql_db_file: '{{ _automationmetrics_db_file.files[0].path }}'

- name: Add postgresql TLS environment variable for certificate authentication
  ansible.builtin.set_fact:
    _common_pg_env: '{{ _common_pg_env | combine(_automationmetrics_pg_ssl) }}'
  vars:
    _automationmetrics_pg_ssl:
      PGSSLCERT: '{{ automationmetrics_config_path }}/postgresql.cert'
      PGSSLKEY: '{{ automationmetrics_config_path }}/postgresql.key'
      PGSSLROOTCERT: '{{ ca_trust_bundle }}'
  when: automationmetrics_pg_cert_auth | bool

- name: Grant createdb role to the automation metrics postgresql user
  community.postgresql.postgresql_user:
    name: '{{ automationmetrics_pg_username }}'
    role_attr_flags: CREATEDB
    login_host: '{{ automationmetrics_pg_host }}'
    login_port: '{{ automationmetrics_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ automationmetrics_pg_socket | default(omit) }}'
  run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Restore the automation metrics postgresql database
  community.postgresql.postgresql_db:
    name: template1
    login_host: '{{ automationmetrics_pg_host }}'
    login_port: '{{ automationmetrics_pg_port }}'
    login_user: '{{ automationmetrics_pg_username }}'
    login_password: '{{ automationmetrics_pg_password | default(omit) }}'
    login_unix_socket: '{{ automationmetrics_pg_socket | default(omit) }}'
    ssl_mode: '{{ automationmetrics_pg_sslmode }}'
    target: '{{ _automationmetrics_db_file.files[0].path }}'
    target_opts: '{{ (_automationmetrics_db_file.files[0].path | split(".") | last == "pgc") | ternary("--create --clean --if-exists", omit) }}'
    state: restore
  environment: '{{ _common_pg_env }}'
  no_log: true
  run_once: true

- name: Revoke createdb role to the automation metrics postgresql user
  community.postgresql.postgresql_user:
    name: '{{ automationmetrics_pg_username }}'
    role_attr_flags: NOCREATEDB
    login_host: '{{ automationmetrics_pg_host }}'
    login_port: '{{ automationmetrics_pg_port }}'
    login_user: '{{ postgresql_admin_username | default("postgres") }}'
    login_password: '{{ postgresql_admin_password | default(omit) }}'
    login_db: '{{ postgresql_admin_database | default("postgres") }}'
    login_unix_socket: '{{ automationmetrics_pg_socket | default(omit) }}'
  run_once: true
  when: groups.get('database', []) | length == 1 or postgresql_admin_password is defined

- name: Initialize data
  ansible.builtin.include_tasks: init.yml

- name: Start automation metrics systemd services
  ansible.builtin.include_tasks: systemd.yml
  vars:
    __systemd_state: started
...
