---
- name: Get all podman secrets
  containers.podman.podman_secret_info:
  register: _secrets

- name: Get the existing automation metrics SECRET_KEY secret
  containers.podman.podman_secret_info:
    name: automationmetrics_secret_key
    showsecret: true
  register: _automationmetrics_secret_key
  no_log: true
  run_once: true
  when: _secrets.secrets | map(attribute='Spec') | selectattr('Name', 'equalto', 'automationmetrics_secret_key') | length > 0

- name: Set the automation metrics SECRET_KEY secret fact
  ansible.builtin.set_fact:
    __automationmetrics_secret_key: >-
      {{ _automationmetrics_secret_key.secrets[0].SecretData
      | default(automationmetrics_secret_key)
      | default(_key_generated) }}
  vars:
    _key_generated: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_letters,digits length=50") }}'
  no_log: true
  run_once: true

- name: Create automation metrics pg_password secret
  containers.podman.podman_secret:
    name: automationmetrics_pg_password
    data: "{{ automationmetrics_pg_password | default(lookup('password', '/dev/null length=32 chars=ascii_letters,digits'), true) }}"
    skip_existing: true
  no_log: true
  notify: Restart automation metrics
  when: not automationmetrics_pg_cert_auth | bool

- name: Create automation metrics controller_read_pg_password secret
  containers.podman.podman_secret:
    name: automationmetrics_controller_read_pg_password
    data: "{{ automationmetrics_controller_read_pg_password | default(lookup('password', '/dev/null length=32 chars=ascii_letters,digits'), true) }}"
    skip_existing: true
  no_log: true
  notify: Restart automation metrics
  when: not automationmetrics_pg_cert_auth | bool

- name: Create automation metrics secret_key secret
  containers.podman.podman_secret:
    name: automationmetrics_secret_key
    data: '{{ __automationmetrics_secret_key }}'
    skip_existing: true
  no_log: true
  notify: Restart automation metrics

- name: Get all podman secrets after update
  containers.podman.podman_secret_info:
  register: _secrets_update

- name: Set automation metrics recreate container fact
  ansible.builtin.set_fact:
    __metrics_recreate: '{{ _metrics_before | difference(_metrics_after) | length > 0 }}'
  vars:
    _metrics_before: '{{ _secrets.secrets | map(attribute="ID") }}'
    _metrics_after: '{{ _secrets_update.secrets | map(attribute="ID") }}'
...
