---
- name: Import postgresql TLS certificate and key
  when:
    - automationmetrics_pg_tls_cert is defined
    - automationmetrics_pg_tls_key is defined
  block:
    - name: Copy postgresql TLS certificate
      ansible.builtin.copy:
        src: '{{ automationmetrics_pg_tls_cert }}'
        dest: '{{ automationmetrics_config_path }}/postgresql.cert'
        mode: '0640'
        remote_src: '{{ automationmetrics_tls_remote | default(false) }}'
      notify: Restart automation metrics

    - name: Copy postgresql TLS key
      ansible.builtin.copy:
        src: '{{ automationmetrics_pg_tls_key }}'
        dest: '{{ automationmetrics_config_path }}/postgresql.key'
        mode: '0400'
        remote_src: '{{ automationmetrics_tls_remote | default(false) }}'
      notify: Restart automation metrics
...
