---
- name: Set facts for containers
  ansible.builtin.set_fact:
    __containers:
      - automation-metrics-service

- name: Set facts for systemd services
  ansible.builtin.set_fact:
    __services: '{{ __containers | product([".service"]) | map("join") | list }}'

- name: Ensure systemd units are disabled and stopped
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: stopped
    enabled: false
    scope: user
  failed_when: false
  loop: '{{ __services }}'

- name: Delete the containers
  containers.podman.podman_container:
    name: '{{ item }}'
    state: absent
  loop: '{{ __containers }}'

- name: Delete the systemd unit files
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/systemd/user/{{ item }}'
    state: absent
  loop: '{{ __services }}'

- name: Delete the automation metrics secrets
  containers.podman.podman_secret:
    name: '{{ item }}'
    state: absent
  loop:
    - automationmetrics_pg_password
    - automationmetrics_controller_read_pg_password
    - automationmetrics_secret_key

- name: Delete the automation metrics directories
  ansible.builtin.file:
    path: '{{ aap_volumes_dir }}/automationmetrics'
    state: absent

- name: Delete firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: disabled
...
