---
- name: Restart lightspeed
  ansible.builtin.systemd:
    name: ansible-lightspeed.service
    scope: user
    state: restarted

- name: Restart lightspeed chatbot
  ansible.builtin.systemd:
    name: ansible-lightspeed-chatbot.service
    scope: user
    state: restarted

- name: Restart lightspeed mcp controller
  ansible.builtin.systemd:
    name: ansible-lightspeed-mcp-controller.service
    scope: user
    state: restarted

- name: Restart lightspeed mcp lightspeed
  ansible.builtin.systemd:
    name: ansible-lightspeed-mcp-lightspeed.service
    scope: user
    state: restarted
...
