---
- name: Allow rootless lightspeed chatbot container to bind from port 80 onwards
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '{{ _lightspeed_chatbot_ports | union(_sysctl_unprivileged_port_start) | min }}'
    sysctl_set: true
    state: present
    reload: true
  become: true
  vars:
    _sysctl_unprivileged_port_start: '[{{ _sysctl_cmd["content"] | b64decode }}]'
  when:
    - lightspeed_chatbot_model_url is defined
    - (_lightspeed_chatbot_ports | min) < 1024

- name: Allow rootless lightspeed mcp-controller container to bind from port 80 onwards
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '{{ _lightspeed_mcp_controller_ports | union(_sysctl_unprivileged_port_start) | min }}'
    sysctl_set: true
    state: present
    reload: true
  become: true
  vars:
    _sysctl_unprivileged_port_start: '[{{ _sysctl_cmd["content"] | b64decode }}]'
  when:
    - lightspeed_mcp_controller_enabled | bool
    - (_lightspeed_mcp_controller_ports | min) < 1024

- name: Allow rootless lightspeed mcp-controller container to bind from port 80 onwards
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '{{ _lightspeed_mcp_lightspeed_ports | union(_sysctl_unprivileged_port_start) | min }}'
    sysctl_set: true
    state: present
    reload: true
  become: true
  vars:
    _sysctl_unprivileged_port_start: '[{{ _sysctl_cmd["content"] | b64decode }}]'
  when:
    - lightspeed_mcp_lightspeed_enabled | bool
    - (_lightspeed_mcp_lightspeed_ports | min) < 1024
...
