---
- name: Set lightspeed mcp-controller env
  ansible.builtin.set_fact:
    _lightspeed_mcp_controller_env:
      HOST: '{{ "*" if ansible_all_ipv6_addresses | length > 0 else "0.0.0.0" }}'
      PORT: '{{ _lightspeed_mcp_controller_port }}'
      AAP_GATEWAY_URL: '{{ hostvars[groups["automationgateway"][0]]["_gateway_proxy_url"] }}'
      AAP_SERVICE_URL: '{{ hostvars[groups["automationcontroller"][0]]["_controller_url"] }}'
  when: lightspeed_mcp_controller_enabled | bool

- name: Set lightspeed mcp-lightspeed env
  ansible.builtin.set_fact:
    _lightspeed_mcp_lightspeed_env:
      HOST: '{{ "*" if ansible_all_ipv6_addresses | length > 0 else "0.0.0.0" }}'
      PORT: '{{ _lightspeed_mcp_lightspeed_port }}'
      AAP_GATEWAY_URL: '{{ hostvars[groups["automationgateway"][0]]["_gateway_proxy_url"] }}'
      AAP_SERVICE_URL: '{{ _lightspeed_instance_url }}'
  when: lightspeed_mcp_lightspeed_enabled | bool
...
