---
- name: Initialize the ansible lightspeed database
  containers.podman.podman_container:
    name: ansible-lightspeed-init
    image: '{{ _lightspeed_image }}'
    command: 'wisdom-manage migrate --noinput'
    detach: false
    rm: true
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    mount:
      - 'type=tmpfs,destination=/etc/ansible/tmp,U=true'
    secrets: '{{ _common_secrets }}'
    volume: '{{ _lightspeed_volumes }}'
    env: '{{ _lightspeed_env }}'
  register: _migrate
  changed_when: "'No migrations to apply' not in _migrate.stdout"
  run_once: true
  retries: 5
  delay: 60
  until: _migrate is not failed

- name: Create django super user
  containers.podman.podman_container:
    name: ansible-lightspeed-init
    image: '{{ _lightspeed_image }}'
    command: 'wisdom-manage createsuperuser --username={{ lightspeed_admin_user }} --email={{ lightspeed_admin_email }} --noinput'
    detach: false
    rm: true
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    mount:
      - 'type=tmpfs,destination=/etc/ansible/tmp,U=true'
    secrets: '{{ _common_secrets }}'
    volume: '{{ _lightspeed_volumes }}'
    env: '{{ _lightspeed_env }}'
  register: _createsuperuser
  changed_when: "'Superuser created successfully' in _createsuperuser.stdout"
  failed_when: false
  run_once: true
  retries: 5
  delay: 60
  until: _createsuperuser is not failed

- name: Initialise the lightspeed chatbot rag content
  containers.podman.podman_container:
    name: ansible-lightspeed-chatbot-init
    image: '{{ _lightspeed_chatbot_image }}'
    command: "/rag/entrypoint.sh"
    detach: false
    rm: true
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    secrets: '{{ _lightspeed_chatbot_secrets }}'
    volume: '{{ _lightspeed_chatbot_volumes }}'
    env: '{{ _lightspeed_chatbot_env }}'
  register: _chatbot_rag_init
  changed_when: >
    ('Latest vector database file has been installed.' in _chatbot_rag_init.stdout) or
    ('Latest embeddings model has been installed.' in _chatbot_rag_init.stdout)
  failed_when: false
  retries: 5
  delay: 60
  until: _chatbot_rag_init is not failed
  when: lightspeed_chatbot_model_url is defined
