---
- name: Get all podman secrets
  containers.podman.podman_secret_info:
  register: _secrets

- name: Create the lightspeed admin password secret
  containers.podman.podman_secret:
    name: lightspeed_admin_password
    data: '{{ lightspeed_admin_password }}'
  notify: Restart lightspeed

- name: Create the lightspeed lightspeed_pg_password secret
  containers.podman.podman_secret:
    name: lightspeed_pg_password
    data: '{{ lightspeed_pg_password }}'
  notify: Restart lightspeed
  when: not lightspeed_pg_cert_auth | bool

- name: Create the lightspeed oauth client_id
  containers.podman.podman_secret:
    name: lightspeed_oauth_client_id
    data: '{{ _lightspeed_oauth_client_id }}'
  notify: Restart lightspeed

- name: Create the chatbot API Key secret
  containers.podman.podman_secret:
    name: lightspeed_chatbot_api_token
    data: '{{ lookup("password", "/dev/null length=32 chars=ascii_letters,digits") }}'
    skip_existing: true
  notify:
    - Restart lightspeed
    - Restart lightspeed chatbot
  when: lightspeed_chatbot_model_url is defined

- name: Get the existing lightspeed oauth client_secret
  containers.podman.podman_secret_info:
    name: lightspeed_oauth_client_secret
    showsecret: true
  register: _lightspeed_client_secret
  no_log: true
  run_once: true
  when: _secrets.secrets | map(attribute='Spec') | selectattr('Name', 'equalto', 'lightspeed_oauth_client_secret') | length > 0

- name: Set the lightspeed oauth client_secret fact
  ansible.builtin.set_fact:
    __lightspeed_oauth_client_secret: '{{ _lightspeed_client_secret.secrets[0].SecretData | default(_lightspeed_oauth_client_secret) }}'
  no_log: true
  run_once: true

- name: Create the lightspeed oauth client_secret
  containers.podman.podman_secret:
    name: lightspeed_oauth_client_secret
    data: '{{ __lightspeed_oauth_client_secret }}'
    skip_existing: true
  notify: Restart lightspeed

- name: Create lightspeed chatbot token
  containers.podman.podman_secret:
    name: lightspeed_chatbot_model_api_key
    data: '{{ lightspeed_chatbot_model_api_key }}'
  notify: Restart lightspeed chatbot
  when: lightspeed_chatbot_model_url is defined

- name: Create the lightspeed model mesh configuration secret
  containers.podman.podman_secret:
    name: lightspeed_model_mesh_config
    data: '{{ lookup("ansible.builtin.template", "lightspeed_model_mesh_conf.j2") }}'
  notify: Restart lightspeed

- name: Get the existing lightspeed secret_key secret
  containers.podman.podman_secret_info:
    name: lightspeed_secret_key
    showsecret: true
  register: _lightspeed_secret_key
  no_log: true
  run_once: true
  when: _secrets.secrets | map(attribute='Spec') | selectattr('Name', 'equalto', 'lightspeed_secret_key') | length > 0

- name: Set the lightspeed secret_key secret fact
  ansible.builtin.set_fact:
    __lightspeed_secret_key: '{{ _lightspeed_secret_key.secrets[0].SecretData | default(lightspeed_secret_key) | default(_key_generated) }}'
  vars:
    _key_generated: '{{ lookup("ansible.builtin.password", "/dev/null chars=ascii_letters,digits length=128") }}'
  no_log: true
  run_once: true

- name: Create the lightspeed secret_key secret
  containers.podman.podman_secret:
    name: lightspeed_secret_key
    data: '{{ __lightspeed_secret_key }}'
    skip_existing: true
  notify: Restart lightspeed

- name: Get the existing lightspeed resource server secret
  containers.podman.podman_secret_info:
    name: lightspeed_resource_server
    showsecret: true
  register: _lightspeed_resource_server
  no_log: true
  run_once: true
  when: _secrets.secrets | map(attribute='Spec') | selectattr('Name', 'equalto', 'lightspeed_resource_server') | length > 0

- name: Set the lightspeed resource server secret fact
  ansible.builtin.set_fact:
    __lightspeed_resource_server: '{{ _lightspeed_resource_server.secrets[0].SecretData | default(_key_generated) }}'
  vars:
    _key_generated: '{{ hostvars[groups["automationgateway"][0]]["__lightspeed_service_key"] }}'
  no_log: true
  run_once: true

- name: Create the lightspeed resource server secret
  containers.podman.podman_secret:
    name: lightspeed_resource_server
    data: '{{ __lightspeed_resource_server }}'
    skip_existing: true
  notify: Restart lightspeed

- name: Get all podman secrets after update
  containers.podman.podman_secret_info:
  register: _secrets_update

- name: Set lightspeed recreate container fact
  ansible.builtin.set_fact:
    __lightspeed_recreate: '{{ _lightspeed_before | difference(_lightspeed_after) | length > 0 }}'
  vars:
    _lightspeed_before: '{{ _secrets.secrets | map(attribute="ID") }}'
    _lightspeed_after: '{{ _secrets_update.secrets | map(attribute="ID") }}'
...
