---
- name: Set facts for systemd services
  ansible.builtin.set_fact:
    __services:
      - ansible-lightspeed.service

- name: Add lightspeed chatbot when available
  ansible.builtin.set_fact:
    __services: '{{ __services | union(["ansible-lightspeed-chatbot.service"]) }}'
  when: lightspeed_chatbot_model_url is defined

- name: Add lightspeed mcp-controller when available
  ansible.builtin.set_fact:
    __services: '{{ __services | union(["ansible-lightspeed-mcp-controller.service"]) }}'
  when: lightspeed_mcp_controller_enabled | bool

- name: Add lightspeed mcp-lightspeed when available
  ansible.builtin.set_fact:
    __services: '{{ __services | union(["ansible-lightspeed-mcp-lightspeed.service"]) }}'
  when: lightspeed_mcp_lightspeed_enabled | bool

- name: Manage ansible lightspeed containers via systemd
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: '{{ __systemd_state | default("started") }}'
    enabled: '{{ __systemd_enabled | default(true) }}'
    scope: user
    daemon_reload: true
  loop: '{{ __services }}'
...
