---
- name: Generate TLS certificate and key
  when:
    - lightspeed_tls_cert is not defined
    - lightspeed_tls_key is not defined
  block:
    - name: Install python-cryptography
      ansible.builtin.package:
        name: python3-cryptography
      become: true
      when: not ostree | bool

    - name: Generate a private key
      community.crypto.openssl_privatekey:
        path: '{{ lightspeed_conf_dir }}/lightspeed.key'
        mode: '0400'
      notify: Restart lightspeed

    - name: Generate a certificate signing request
      community.crypto.openssl_csr:
        path: '{{ lightspeed_conf_dir }}/lightspeed.csr'
        privatekey_path: '{{ lightspeed_conf_dir }}/lightspeed.key'
        common_name: '{{ _lightspeed_hostname }}'
        country_name: 'US'
        locality_name: 'Raleigh'
        organization_name: 'Red Hat'
        organizational_unit_name: 'Ansible'
        state_or_province_name: 'North Carolina'
        subject_alt_name: '{{ [_lightspeed_hostname | ansible.containerized_installer.subject_alt_name] | union(_lightspeed_ips) }}'
        mode: '0640'

    - name: Generate a self signed x509 certificate
      community.crypto.x509_certificate:
        path: '{{ lightspeed_conf_dir }}/lightspeed.cert'
        csr_path: '{{ lightspeed_conf_dir }}/lightspeed.csr'
        privatekey_path: '{{ lightspeed_conf_dir }}/lightspeed.key'
        provider: ownca
        ownca_path: '{{ _ca_tls_dir }}/ca.cert'
        ownca_privatekey_path: '{{ _ca_tls_dir }}/ca.key'
        ownca_privatekey_passphrase: '{{ ca_tls_key_passphrase | default(omit) }}'
        mode: '0640'
      notify: Restart lightspeed

- name: Import TLS certificate and key
  when:
    - lightspeed_tls_cert is defined
    - lightspeed_tls_key is defined
  block:
    - name: Copy lightspeed TLS certificate
      ansible.builtin.copy:
        src: '{{ lightspeed_tls_cert }}'
        dest: '{{ lightspeed_conf_dir }}/lightspeed.cert'
        mode: '0640'
        remote_src: '{{ lightspeed_tls_remote | default(false) }}'
      notify: Restart lightspeed

    - name: Copy lightspeed TLS key
      ansible.builtin.copy:
        src: '{{ lightspeed_tls_key }}'
        dest: '{{ lightspeed_conf_dir }}/lightspeed.key'
        mode: '0400'
        remote_src: '{{ lightspeed_tls_remote | default(false) }}'
      notify: Restart lightspeed
...
