---
- name: Import postgresql TLS certificate and key
  when:
    - lightspeed_pg_tls_cert is defined
    - lightspeed_pg_tls_key is defined
  block:
    - name: Copy postgresql TLS certificate
      ansible.builtin.copy:
        src: '{{ lightspeed_pg_tls_cert }}'
        dest: '{{ lightspeed_conf_dir }}/postgresql.cert'
        mode: '0640'
        remote_src: '{{ lightspeed_tls_remote }}'
      notify: Restart lightspeed

    - name: Copy postgresql TLS key
      ansible.builtin.copy:
        src: '{{ lightspeed_pg_tls_key }}'
        dest: '{{ lightspeed_conf_dir }}/postgresql.key'
        mode: '0400'
        remote_src: '{{ lightspeed_tls_remote }}'
      notify: Restart lightspeed
...
