---
- name: Define _mcp_env
  ansible.builtin.set_fact:
    _mcp_env:
      BASE_URL: '{{ mcp_public_base_url or hostvars[groups["automationgateway"][0]]["_gateway_proxy_url"] }}'
      IGNORE_CERTIFICATE_ERRORS: '{{ mcp_ignore_certificate_errors }}'
      ALLOW_WRITE_OPERATIONS: '{{ mcp_allow_write_operations }}'

- name: Add extra_settings variables
  ansible.builtin.set_fact:
    _mcp_env: '{{ _mcp_env | combine({item.setting: item.value}) }}'
  loop: '{{ mcp_extra_settings }}'

- name: Create the ansiblemcp container
  containers.podman.podman_container:
    name: ansiblemcp
    image: '{{ _mcp_image }}'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    mount:
      - 'type=tmpfs,destination=/run/nginx,U=true'
    volume: '{{ _mcp_volumes }}'
    label: '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
    env: '{{ _mcp_env }}'
  notify: Restart ansiblemcp
...
