---
- name: Set ansiblemcp ports fact
  ansible.builtin.set_fact:
    _mcp_ports: ['{{ mcp_nginx_http_port }}']

- name: Add https port to gateway port list
  ansible.builtin.set_fact:
    _mcp_ports: '{{ _mcp_ports | union([mcp_nginx_https_port]) }}'
  when: not mcp_nginx_disable_https | bool

- name: Ensure systemd units are disabled and stopped
  ansible.builtin.systemd:
    name: 'ansiblemcp.service'
    state: stopped
    enabled: false
    scope: user
  failed_when: false

- name: Delete the containers
  containers.podman.podman_container:
    name: 'ansiblemcp'
    state: absent

- name: Delete the systemd unit files
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/systemd/user/ansiblemcp.service'
    state: absent

- name: Delete podman volumes
  ansible.builtin.include_tasks: volumes.yml
  vars:
    __volume_state: absent

- name: Delete the ansiblemcp directories
  ansible.builtin.file:
    path: '{{ aap_volumes_dir }}/ansiblemcp'
    state: absent

- name: Delete ansiblemcp firewalld rules
  ansible.builtin.include_tasks: firewalld.yml
  vars:
    __firewalld_state: disabled
...
