---
- name: Revert host tuning changes
  block:
    - name: Remove AAP sysctl configuration
      ansible.builtin.file:
        path: /etc/sysctl.d/99-aap.conf
        state: absent
      become: true

    - name: Remove AAP limits configuration file
      ansible.builtin.file:
        path: /etc/security/limits.d/99-aap-limits.conf
        state: absent
      become: true
